#  Here i will cover the most fundamental concept of tensors using Tensorflow

#Introduction to Tensors


In [3]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [4]:
# Creating tensor with tf.constant()
scalar = tf.constant(7)
print(scalar)

tf.Tensor(7, shape=(), dtype=int32)


In [5]:
# Number of simension of a tensor(ndim stands for number of dimensions)
scalar.ndim

0

In [6]:
# create a vector
vector = tf.constant([10 , 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
# create a matrix (has more than 1 dimension)
matrix = tf.constant([[1,4,7],
                     [5,4,3]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 4, 7],
       [5, 4, 3]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
# create another matrix
another_matrix = tf.constant([[10. , 7.],
                             [4. , 2.],
                             [9. , 2.]] , dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 4.,  2.],
       [ 9.,  2.]], dtype=float16)>

In [11]:
# number of dimension of another matrix
another_matrix.ndim

2

In [12]:
# lets create  a tensor
tensor = tf.constant([[[1,2,3,],
                      [3,4,6]],
                     [[4,6,8],
                      [7,8,9]],
                     [[2,5,6],
                      [6,5,4]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [3, 4, 6]],

       [[4, 6, 8],
        [7, 8, 9]],

       [[2, 5, 6],
        [6, 5, 4]]], dtype=int32)>

In [13]:
tensor.ndim

3

 creting tensors with tf.variable

In [14]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [15]:
# create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10 , 7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [16]:
# change the emplent in changeable tensor
changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [17]:
# how about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [18]:
# lets change unchanmgeable tensors
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Creating random tensors

In [ ]:
# create two random (but the same ) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3 ,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# are they eual
random_1 , random_2 , random_1==random_2

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

Shuffle the order in tensor

In [ ]:
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
# shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled)

In [ ]:
# shuffle our non_shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled  , seed=42)

In [ ]:
tensor_0 =tf.constant([[1,2],
                       [4,5],
                       [7,8]])
tensor_0

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,3))
random_1

In [ ]:
import tensorflow as tf
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(2,3))
random_2

In [19]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(4,3))
random_3

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 ],
       [-0.57166284,  0.1480774 , -0.23362993]], dtype=float32)>

In [20]:
random_4 = tf.random.Generator.from_seed(42)
random_4 = random_4.normal(shape=(5,3))
random_4

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 ],
       [-0.57166284,  0.1480774 , -0.23362993],
       [-0.3522796 ,  0.40621263, -1.0523509 ]], dtype=float32)>

In [21]:
random_5 = tf.random.Generator.from_seed(42)
random_5 = random_5.normal(shape=(4,3))
random_5

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 ],
       [-0.57166284,  0.1480774 , -0.23362993]], dtype=float32)>

In [22]:
random_6 = tf.random.Generator.from_seed(2)
random_6 = random_6.normal(shape=(2,2))
random_6

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.1012345, -0.2744976],
       [ 1.4204658,  1.2609464]], dtype=float32)>

Tensors and shufflle them ( practice it )

In [23]:
import tensorflow as tf
tensor_1 = tf.constant([[1,2,3],
                        [4,3,1]])

In [24]:
tf.random.shuffle(tensor_1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 3, 1]], dtype=int32)>

In [25]:
tf.random.set_seed(42)   #  what is difference between from and set seed
tf.random.shuffle(tensor_1 ,seed=42)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 3, 1],
       [1, 2, 3]], dtype=int32)>

In [26]:
tensor_2 = tf.constant([[1,2,3],
                        [4,5,6],
                        [7,9,6]])

In [27]:
tf.random.shuffle(tensor_2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 9, 6],
       [1, 2, 3]], dtype=int32)>

In [28]:
tf.random.set_seed(42)
tf.random.shuffle(tensor_2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 9, 6],
       [1, 2, 3]], dtype=int32)>

In [29]:
tensor_3 = tf.constant([[1,2,3,4,5],
                       [5,4,3,2,1],
                        [7,8,9,5,4]])
tf.random.shuffle(tensor_3)

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[7, 8, 9, 5, 4],
       [1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]], dtype=int32)>

In [30]:
tf.random.set_seed(42)
tf.random.shuffle(tensor_3 , seed=42)

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [7, 8, 9, 5, 4]], dtype=int32)>

In [31]:
tensor_4 = tf.constant([[1,2,3],
                        [6,7,8],
                        [7,8,9]])
tf.random.shuffle(tensor_4)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 7, 8],
       [7, 8, 9],
       [1, 2, 3]], dtype=int32)>

In [32]:
tf.random.set_seed(42)
tf.random.shuffle(tensor_4)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 7, 8],
       [7, 8, 9],
       [1, 2, 3]], dtype=int32)>

In [33]:
tensor_5 =tf.constant([[3,2,1],
                       [5,6,7],
                       [8,7,6]])
tf.random.shuffle(tensor_5)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[8, 7, 6],
       [3, 2, 1],
       [5, 6, 7]], dtype=int32)>

In [34]:
tf.random.set_seed(42) # global level seed
tf.random.shuffle(tensor_5 , seed=42)  # operation level seed

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 2, 1],
       [5, 6, 7],
       [8, 7, 6]], dtype=int32)>

other ways to make tensors

In [35]:
# creats the tensors of ones
tf.ones([3,5]) # defines the shape of tensor

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [36]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [37]:
tf.zeros(shape=(3 , 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy array into tensors

The main difference between numpy arrays and tensorlow tensors is that tensors can be run on GPU(much faster for numerical computing)

In [38]:
# you can also trun numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1 , 25  ,dtype= np.int32)

numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [39]:
A = tf.constant(numpy_A , shape=(2, 3 , 4))   #  First is block , Second is rows , Third is columns
B = tf.constant(numpy_A)                      #  2*3*4 = 24

A , B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [40]:
  3 * 2 * 4  ,  3 * 8

(24, 24)

In [41]:
A.ndim , B.ndim

(3, 1)

In [42]:
# converting an array to the tensor directly
numpy_B = np.arange(2,13)
B =tf.constant(numpy_B)
B

<tf.Tensor: shape=(11,), dtype=int64, numpy=array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])>

### Getting information from tensors
when dealing with tensor you probably want to be aware of the following attributes:
* shape
*rank
*axis or dimenstion
*size

In [43]:
# create a rank 4 tensor(4 dimensions)
rank_4_tensor = tf.zeros(shape=[2 , 3 , 4 , 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [44]:
rank_4_tensor.ndim

4

In [45]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [46]:
rank_4_tensor.shape , rank_4_tensor.ndim  , tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [47]:
2*3*4*5

120

In [48]:
# Getting various attributes of our tensor
print("DataType of every element :", rank_4_tensor.dtype)
print("Number of dimensions (rank):",rank_4_tensor.ndim)
print("shape of tensor :", rank_4_tensor.shape)
print("Elements along the 0 axis :", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor :", tf.size(rank_4_tensor))
print("Total number of elements in our tensor :", tf.size(rank_4_tensor).numpy())

DataType of every element : <dtype: 'float32'>
Number of dimensions (rank): 4
shape of tensor : (2, 3, 4, 5)
Elements along the 0 axis : 2
Elements along the last axis: 5
Total number of elements in our tensor : tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor : 120


### Indexing tensors
Tensors can be indexed just like python lists

In [49]:
some_list = [1 ,2 ,3 ,4, 5,6]
some_list[:5]

[1, 2, 3, 4, 5]

In [50]:
rank_4_tensor[:2 ,:2 ,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [51]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [52]:
rank_4_tensor[:2 ,:2 ,:2 ,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [53]:
tensor_5 = tf.zeros(shape=([2,3,4]))
tensor_5

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [54]:
rank_4_tensor[:2 ,:2 ,:2]

<tf.Tensor: shape=(2, 2, 2, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [55]:
# create two tensors (2 dimensions)
rank_2_tensor = tf.constant([[10 , 7],
                            [12 , 4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [12,  4]], dtype=int32)>

In [56]:
 rank_2_tensor.ndim   # number of dimensions

2

In [57]:
some_list  , some_list[-1]

([1, 2, 3, 4, 5, 6], 6)

In [58]:
# get the last item of each of row of our rank_2_tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [59]:
# Add  in extra dimensions to our rank_2_tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[12],
        [ 4]]], dtype=int32)>

In [60]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) # -1 means expandthe final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[12],
        [ 4]]], dtype=int32)>

In [61]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [12,  4]]], dtype=int32)>

In [62]:
tf.expand_dims(rank_2_tensor,axis=0)   # expands the zero axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [12,  4]]], dtype=int32)>

In [63]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [12,  4]], dtype=int32)>

# Manipulating  tensors (tensor operations)

 Basic Operations :
 / ,* ,+,-

In [64]:
# you can add values to a tensor using the addition operator
tensor = tf.constant([[10 , 7], [12 , 4]])
tensor+5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 12],
       [17,  9]], dtype=int32)>

In [65]:
# original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [12,  4]], dtype=int32)>

In [66]:
# Multiplication also works
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 35],
       [60, 20]], dtype=int32)>

In [67]:
# Subtraction if you want
tensor - 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  2],
       [ 7, -1]], dtype=int32)>

In [68]:
# we can also use tensorflow built in function  too
tf.multiply(tensor , 3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 21],
       [36, 12]], dtype=int32)>

In [69]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [12,  4]], dtype=int32)>

## **Matrix Multiplication**
In Machine learning matrix multiplication is one of the most common tensors operations.

In [70]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor , tensor)

tf.Tensor(
[[10  7]
 [12  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[184,  98],
       [168, 100]], dtype=int32)>

In [71]:
x =tf.constant([1,2,3,4])
tf.multiply(x ,x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16], dtype=int32)>

In [72]:
y = tf.ones([2,1])
x = tf.ones([1,2])
tf.multiply(x,y)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [74]:
# Matrix Multiplication with Python Operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[184,  98],
       [168, 100]], dtype=int32)>

In [76]:
tensor.shape

TensorShape([2, 2])

In [77]:
# creatre a tensor (3 , 2) tensor
x = tf.constant([[1 ,2],
                 [3,4],
                 [7,6]])
y = tf.constant([[4,3],
                 [6,7],
                 [8,9]])
x , y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[4, 3],
        [6, 7],
        [8, 9]], dtype=int32)>)

In [78]:
x @ y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [90]:
a = tf.constant([[1,2],
                 [4,5],
                 [7,6]])
b = tf.constant([[5,6, 3],
               [7,8 ,6],

                 ])
a , b

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [4, 5],
        [7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[5, 6, 3],
        [7, 8, 6]], dtype=int32)>)

In [93]:
tf.reshape(y ,shape=(3,2))    # from   the tf.reshape   we can change the shape of the matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 7],
       [8, 9]], dtype=int32)>

In [101]:
# matmul  with 1 tensor and other  is tf.reshape
a @ tf.reshape(b ,shape=(2 , 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[19, 22, 15],
       [55, 64, 42],
       [77, 90, 57]], dtype=int32)>

In [98]:
# transpose and  tf.reshape
tf.transpose(a), tf.reshape(a , shape=(3,2))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 4, 7],
        [2, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [4, 5],
        [7, 6]], dtype=int32)>)

In [102]:
# trying  multiplication with transpose rather than reshape
tf.matmul(a ,tf.transpose(a))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 14, 19],
       [14, 41, 58],
       [19, 58, 85]], dtype=int32)>

In [105]:
tf.matmul(tf.transpose(a) ,a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[66, 64],
       [64, 65]], dtype=int32)>

**The Dot Product**

matrix multiplication  is alos referred to as dot product.

you can perfrom matrix multiplication using:
* tf.matmul()
*tf.tensordot()
* @

In [106]:
x , y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[4, 3],
        [6, 7],
        [8, 9]], dtype=int32)>)

In [120]:
# perform thedot product on  x , y (requires x or y to be transposed)
tf.tensordot(x , tf.transpose(y) , axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 10,  20,  26],
       [ 24,  46,  60],
       [ 46,  84, 110]], dtype=int32)>

In [126]:
# Check the values of Y , reshape y and transpose of y
print("Normal Y")
print(y , " \n ")  # \n for new line

print("Y reshaped to (2 ,3)")
print(tf.reshape(y,shape=(2 ,3)), "\n")

print("Y  Transpose ")
print(tf.transpose(y))

Normal Y
tf.Tensor(
[[4 3]
 [6 7]
 [8 9]], shape=(3, 2), dtype=int32)  
 
 Y reshaped to (2 ,3)
tf.Tensor(
[[4 3 6]
 [7 8 9]], shape=(2, 3), dtype=int32) 

Y  Transpose 
tf.Tensor(
[[4 6 8]
 [3 7 9]], shape=(2, 3), dtype=int32)


In [127]:
tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 10,  20,  26],
       [ 24,  46,  60],
       [ 46,  84, 110]], dtype=int32)>

Generally  , when performing matrix multiplication on two tensors and one of the axes doesn't line up , you will transpose (rather than reshape) one of the tensors to get satisfy the matrix multiplication rules

**Changing the datatype of a tensor**





In [6]:
tf.__version__

'2.18.0'

In [10]:
# create a new tensor with default datatype  (float32)
B = tf.constant([1.7 , 4.5])
B ,B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 4.5], dtype=float32)>,
 tf.float32)

In [13]:
C = tf.constant([7 , 10])
C , C.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 tf.int32)

In [11]:
# change float32 to float16 (refuced precision)
D = tf.cast(B , dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 4.5], dtype=float16)>

In [15]:
E =tf.cast(C , dtype=tf.int16)
E

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([ 7, 10], dtype=int16)>

In [18]:
F = tf.cast(C , dtype=tf.float16)
F.dtype , F

(tf.float16,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>)

**Aggregating Tensors**

Aggregating tensors = considering them from multiple values down to a smaller amount of values

Aggregating a tensor means reducing it into a smaller shape or single value by applying operations like:

Sum

Mean

Max / Min

Prod (product)

In [3]:
# get the absolute value
D = tf.constant([-7 , 10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-7, 10], dtype=int32)>

In [4]:
# get the absolute value
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [19]:
# create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0 ,100 , size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 1, 63, 48, 61, 76, 75, 88, 49, 11, 93, 41, 37, 38, 37, 18, 43, 58,
       88, 78, 52, 54, 60, 17, 96, 75, 86, 49, 42, 69, 34,  8, 10, 16,  8,
       55,  4, 52, 12, 57, 73, 23, 10, 79, 53, 89, 32, 80, 73, 93, 38])>

In [20]:
tf.size(E) , E.shape , E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [21]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [22]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [24]:
# Find the sum of the tensor
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2502>

In [29]:
# variance
F= tf.cast(E, dtype=tf.float16)
variance = tf.math.reduce_variance(F)
variance.numpy()

np.float16(751.5)

In [33]:
# Standard Deviation
st_dev = tf.math.reduce_std(F)
st_dev.numpy()

np.float16(27.4)

In [37]:
import tensorflow_probability as tfp
# Find the Variance
var = tfp.stats.variance(E)
var.numpy()

np.int64(751)

In [47]:
# find the Stand Deviation
std = tfp.stats.stddev(F)   # requires the tensors only in datatype of  float
std.numpy()

np.float16(27.4)

### Find the positional maximum and minimum

In [21]:
# Maximum
x = tf.constant([1,1.1,3.1,7,9 ,55])
X =tf.cast(x ,dtype=tf.int32)
y = tf.constant([3,4,5,6,88,7])

In [23]:
# maximum
tf.math.maximum(X,y)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 3,  4,  5,  7, 88, 55], dtype=int32)>

In [24]:
# Minimum
tf.minimum(X,y)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 1, 3, 6, 9, 7], dtype=int32)>

In [27]:
a = tf.constant([1.1 , 4.3 , 5.5])
b = tf.constant([0.1 , 2.3 , 4.3])


In [37]:
tf.maximum(a ,b).numpy() ,tf.minimum(b,a).numpy()

(array([1.1, 4.3, 5.5], dtype=float32), array([0.1, 2.3, 4.3], dtype=float32))

In [46]:
# creating a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape =[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [47]:
# find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [48]:
# index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [49]:
# find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [55]:
# chack for equality
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [56]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [58]:
# find the positinal minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [59]:
# find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

In [62]:
A =tf.random.uniform(shape=[45])
A

<tf.Tensor: shape=(45,), dtype=float32, numpy=
array([0.7402308 , 0.33938193, 0.5692506 , 0.44811392, 0.29285502,
       0.4260056 , 0.62890387, 0.691061  , 0.30925727, 0.89236605,
       0.66396606, 0.30541587, 0.8724164 , 0.1025728 , 0.56819403,
       0.25427842, 0.7253866 , 0.4770788 , 0.46289814, 0.88944995,
       0.6792555 , 0.09752727, 0.01609659, 0.4876021 , 0.5832968 ,
       0.41212583, 0.731905  , 0.93418944, 0.5298122 , 0.9664817 ,
       0.88391197, 0.10578597, 0.44439578, 0.7851516 , 0.47332513,
       0.89893615, 0.04290593, 0.8717004 , 0.6068529 , 0.12963045,
       0.4527359 , 0.24573493, 0.34777248, 0.582147  , 0.82298195],
      dtype=float32)>

In [63]:
# find the position of maximum
tf.argmax(A)

<tf.Tensor: shape=(), dtype=int64, numpy=29>

In [68]:
# find the max value of A
tf.reduce_max(A)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9664816856384277>

In [70]:
# find the maximum using the positional maximum index
A[tf.argmax(A)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9664816856384277>

In [72]:
# check for equality
A[tf.argmax(A)] == tf.reduce_max(A)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [74]:
# positional minimum
tf.argmin(A)

<tf.Tensor: shape=(), dtype=int64, numpy=22>

In [73]:
# mini value of A
tf.reduce_min(A)

<tf.Tensor: shape=(), dtype=float32, numpy=0.01609659194946289>

In [80]:
# FIND THE MINIMUM using the positional minimum index
A[tf.argmin(A)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.01609659194946289>

### Squezzing the \Tensor (removing all single dimensions)

In [84]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape =(1 ,1 ,1 , 50))
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [85]:
G.shape

TensorShape([1, 1, 1, 50])

In [87]:
G_squeezed = tf.squeeze(G)
G_squeezed , G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

In [94]:
tf.size(G_squeezed).numpy()

np.int32(50)

### One hot encoding tensors

In [113]:
# Create a list of  indices
some_list = [0, 1 , 2 ,3 ] # could be  red , green ,blue  , yellow

# one hot encode our list of indices
tf.one_hot(some_list , depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [109]:
tf.one_hot(some_list , depth=4  , on_value="Ai" ,off_value="love")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Ai', b'love', b'love', b'love'],
       [b'love', b'Ai', b'love', b'love'],
       [b'love', b'love', b'Ai', b'love'],
       [b'love', b'love', b'love', b'Ai']], dtype=object)>

### Squaring Log Square root

In [119]:
# create a new tensor
H = tf.range(1 ,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [122]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [126]:
# squareroot will error , method requires not int dtype
tf.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

In [124]:
# find the squareroot
tf.sqrt(tf.cast(H , dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [130]:
# find the log(logrithm)  dtype should be in float
tf.math.log( tf.cast(H,  dtype= tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

In [136]:
# create a tensor directory  from a numpy array
J =tf.constant(np.array([3., 7. , 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [137]:
# convert our tensor back to a Numpy array
np.array(J)  ,type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [138]:
# convert J to a Numpy array
J.numpy() , type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [142]:
J= tf.constant([4.])
J.numpy()[0]

np.float32(4.0)

In [146]:
# The default types of each  are slighly different
numpy_J =tf.constant(np.array([3. ,4., 7.]))
tensor_J =tf.constant([3. ,4. , 7.])

# checking the datatypes
numpy_J.dtype , tensor_J.dtype

(tf.float64, tf.float32)